### PR TITLE
add required/optional section

### LINKED ISSUE #103: Document the ability and circumstances for using required & optional: null
Now that we are allowing for task ID properties to both be set to `null` when a task ID is not relevant to certain modeling task but is for others, we need to add some documentation about this

### PR DESCRIPTION
**Pull request by LucieContamin**
fix #103

### CODE REVIEW

**Review by annakrystalli — APPROVED** [review]
Thank @LucieContamin . Overall looks great, I just took the liberty to make some minor edits and also tidy up the heading and correct a long standing issue (#81) where we were demonstrating using trailing zeros in quantile output type id values which is wrong.

Feel free to review my own contribution and change anything you think is not right!

**Comment by micokoch** [comment]
Thanks for doing all this. I made some edits in places where I thought the explanation could be a bit more clear. Please take a look and check I didn't mess up the explanation. I will approve my review, but hold off on merging.

**Review by micokoch — COMMENTED** [review]
I made some direct edits - please review. Thank you!

**Review by micokoch — APPROVED** [review]

**Comment by LucieContamin** [comment]
Thanks!

**Pull request merged**
