### PR TITLE
Update docs for cloud-enabled schema (v2.0.1)

### LINKED ISSUE #89: Add documentation for optional configuration of a cloud backend
As part of the [Hubverse Cloud project](https://github.com/orgs/Infectious-Disease-Modeling-Hubs/projects/5/views/1), update Hubverse documentation to include the following:

- [ ]  Background/overview of what a cloud-enabled hub does and how it works
- [ ] How to set up admin config for cloud-enabled hubs

### PR DESCRIPTION
**Pull request by bsweger**
Resolves #89 

Bump the schema version and add some information about cloud-enabled hubs.

### CODE REVIEW

**Comment by bsweger** [comment]
These changes feel like they might not be enough information for people to decide if they should use cloud storage (for example, how does it work?)

Would be grateful for suggestions on a useful level of detail and where we might put additional info. Or perhaps it makes sense to start with this minimal information and iterate based on feedback?

**Comment by micokoch** [comment]
I vote to merge it and iterate as needed. If there are improvements, they can be documented as they happen.

**Comment by bsweger** [comment]
@micokoch Makes sense--better to get something out there that reflects the recent `admin.json` schema change!

Taking your advice, will remove the PR's draft label 😄

**Review by micokoch — APPROVED** [review]
Looks good to me.

**Review by annakrystalli — APPROVED** [review]
I agree @bsweger that more details on what's on offer is eventually required, ideally in a new page that we can add to as the cloud infrastructure is further developed. But for now I think this is fine to merge. Perhaps opening an issue where we can sketch out what should be in the new cloud page might be a good idea.

**Pull request merged**
