### PR TITLE
Clarify model output conventions

### PR DESCRIPTION
**Pull request by micokoch**

### CODE REVIEW

**Comment by micokoch** [comment]
Addresses issue #115 .

**Comment by micokoch** [comment]
@lshandross @elray1 @nickreich - Here is the PR I mentioned, and I added the reference to the hubEnsembles manuscript. Hope that works for you all.

**Review by nickreich — CHANGES_REQUESTED** [review]
Thanks for this PR! I'd suggest not including the journal name, as it hasn't been accepted yet. Otherwise, LGTM.

**Review by lshandross — COMMENTED** [review]
If we decide that this method of explaining model output conventions where we include the `value` column in the "model output representation columns" (as opposed to `value` being its own type of column), I'm fine with this wording. More discussion on the original issue, Issue #115

**Pull request closed without merging**
