### PR TITLE
Adding a Software section

### PR DESCRIPTION
**Pull request by micokoch**

### CODE REVIEW

**Comment by micokoch** [comment]
Hi @annakrystalli - I heard you are not available this week, but for when you return, I made some simple formatting and text edits. Thank you!

**Review by nickreich — CHANGES_REQUESTED** [review]
Thanks for the PR @micokoch . Here are a few small comments and suggestions:
 - for hubUtils, can you provide the link to the pkgdown site? currently, the software page links out only to the GitHub repo, not the more user-friendly site. https://infectious-disease-modeling-hubs.github.io/hubUtils/
 - for the hubTemplate section, I think it would be better to break this up into a more general section about "getting started with the hubverse" or something like that, with links to the hubTemplate repo (which isn't really software, but rather a template repo for data storage, and is also somewhat in development still) and links to the example repos that are also part of the consortium project. Maybe even providing links to the example repos that correspond to each hub? E.g. the example simple forecast hub is kind of like the US forecast Hub and the example complex scenario hub is kind of like the scenario hub.

**Comment by micokoch** [comment]
Hello. I added a new section "Getting started" that has information on the examples and template. There is a fair amount of redundancy from the landing page (the same is true of the software section), so perhaps some of the details can be removed from the landing page with simple pointers to the subsections? I could also add a few more details about each of the examples.

**Comment by micokoch** [comment]
Hello. I made the edits as best I understood them. I kept some of the redundancies in the landing page, because I was unsure how much to chop off. Let me know what other changes are needed.

**Review by nickreich — COMMENTED** [review]
What would you think about just deleting everything on index.md from "Tools for building and hosting modeling hubs" and below, since now it is all duplicated elsewhere?

**Comment by micokoch** [comment]
I just finished those updates. Let me know if there are any problems.

**Review by nickreich — APPROVED** [review]

**Comment by annakrystalli** [comment]
Sure. I actually need to merge the new schema version branch at the same time too and make new releases in each repo. Do you mind if I tackle this on Monday when I'm back on the project?

**Comment by nickreich** [comment]
sounds perfect. thanks!

**Comment by annakrystalli** [comment]
Sorry I thought you meant merge into `main`. I actually think we're ready to go ahead and release version 1.0.0 of docs and schema. Should I go ahead and do that on Monday?

**Comment by nickreich** [comment]
All good. I was suggesting only merging into the branch, which you did. I defer to you on the right timing for releasing 1.0.0. I haven't been tracking closely all the associated threads/changes. Happy to discuss more if it'd be helpful.

**Pull request merged**
